first update

diff --git a/.jenkins/Jenkinsfile b/.jenkins/Jenkinsfile
--- a/.jenkins/Jenkinsfile
+++ b/.jenkins/Jenkinsfile
@@ -7,7 +7,50 @@ pipeline {
         stage('Build') {
             agent { label 'build' }
             steps {
-                echo "hello world ..."
+                script {
+                    def filesInThisCommitAsString = sh(script:"git diff --name-only HEAD~1..HEAD | grep '^.jenkins/' || echo -n ''", returnStatus: false, returnStdout: true).trim()
+                    def hasChangesInPath = (filesInThisCommitAsString.length() > 0)
+                    echo "${filesInThisCommitAsString}"
+                    if (!currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') && !hasChangesInPath){
+                        currentBuild.rawBuild.delete()
+                        error("No changes detected in the path ('^.jenkins/')")
+                    }
+                }
+                echo "Aborting all running jobs ..."
+                script {
+                    abortAllPreviousBuildInProgress(currentBuild)
+                }
+                echo "BRANCH_NAME:${env.BRANCH_NAME}\nCHANGE_ID:${env.CHANGE_ID}\nCHANGE_TARGET:${env.CHANGE_TARGET}"
+                echo "Building ..."
+                sh "cd .jenkins/.pipeline && ./npmw build -- --pr=${CHANGE_ID}"
+            }
+        }
+        stage('Deploy (DEV)') {
+            agent { label 'deploy' }
+            steps {
+                echo "Deploying ..."
+                sh "cd .jenkins/.pipeline && DEBUG=info* ./npmw deploy -- --pr=${CHANGE_ID} --env=dev"
+            }
+        }
+        stage('Deploy (PROD)') {
+            agent { label 'deploy' }
+            input {
+                message "Should we continue with deployment to PROD?"
+                ok "Yes!"
+            }
+            steps {
+                echo "Deploying ..."
+                sh "cd .jenkins/.pipeline && ./npmw deploy -- --pr=${CHANGE_ID} --env=prod"
+            }
+        }
+        stage('Acceptance') {
+            agent { label 'deploy' }
+            input {
+                message "Should we continue with cleanup?"
+                ok "Yes!"
+            }
+            steps {
+                echo "Cleaning ..."
             }
         }
     }
